language: python
matrix:
  include:
  - python: "3.9"
    env: TOX_ENV=flake8
  - python: "3.9"
    env: TOX_ENV=check_rst
  - python: "3.9"
    env: TOX_ENV=py39
  - python: "3.9"
    env: TOX_ENV=coverage
cache:
  directories:
    - $HOME/.cache/pip/http/
    - $HOME/build/nitmir/policyd-rate-limit/.tox/$TOX_ENV/
install:
  - "travis_retry pip install setuptools --upgrade"
  - "pip install tox"
script:
  - tox -e $TOX_ENV
after_script:
  - cat tox_log/*.log
